[project]
name = "sensors-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "holidays>=0.90",
    "numpy>=2.4.1",
    "pytest>=9.0.2",
    "uvicorn==0.40.0",
    "fastapi==0.128.0"
]
